name: Run code and send email with results
on:
  schedule:
    # https://crontab.guru/#10_18_*_*_2,4
    - cron: 55 55 55 55 55
  workflow_dispatch:
    # inputs:
    #   should_send_email:
    #     description: Send Email
    #     required: false
    #     type: boolean

jobs:
  run_code:
    runs-on: ubuntu-latest
    steps:
      # - run: |
      #     echo "Should Send Email: $SHOULD_SEND_EMAIL"
      #   env:
      #     SHOULD_SEND_EMAIL: ${{ inputs.should_send_email }}
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.2.0
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # install the python version needed
          cache: "pipenv" # caching pip dependencies
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install --user pipenv
          pipenv install
      - name: execute python script # run main.py
        run: pipenv run start_main
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          PORT: ${{ secrets.PORT }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SHOULD_SEND_EMAIL: ${{ secrets.SHOULD_SEND_EMAIL }}
          RECEIVERS: ${{ secrets.RECEIVERS }}
