name: Run code and send email with results
on:
  schedule:
    # https://crontab.guru/#5_4_*_*_1,2,3,4,5
    - cron: "10 18 * * 1,2,3,4,5"
  workflow_dispatch:
    inputs:
      should_send_email:
        description: Send Email
        required: false
        type: boolean

jobs:
  run_code:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Should Send Email: $SHOULD_SEND_EMAIL"
        env:
          SHOULD_SEND_EMAIL: ${{ inputs.should_send_email }}
      - uses: logikal-io/install-chrome@v1
        with:
          version: 112.0.5615.137
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # install the python version needed
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install --user pipenv
          pipenv install
      - name: execute python script # run main.py
        run: pipenv run start_main
