name: Run code and send an email with results
on:
  schedule:
    - cron: "10 18 * * *" # every end of the day
    #- cron: */10 * * * *" # every 10 minutes

jobs:
  run_code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # install the python version needed
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install --user pipenv
          pipenv install
      - name: execute python script # run main.py
        run: pipenv run main.py
